apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-msuy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-msuy@sha256:be6d77aa81baf5e03405fd36738e62a057216dd56cc2af7fb126b93c7c035c8e
        name: my-nodejs
        resources: {}
status: {}
